package com.qwwuyu.recite.bean;

import android.os.Parcel;
import android.os.Parcelable;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.NotNull;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Update by qw on 2016/8/22.
 */
@Entity
public class Word implements Parcelable {

    /**
     * id
     */
    @Id(autoincrement = true)
    private long id;

    /**
     * 单词文本
     */
    @NotNull
    private String text;
    /**
     * 音标
     */
    private String accents;
    /**
     * 单词介绍
     */
    private String content;
    /**
     * 乱序角标
     */
    private int index;
    /**
     * 收藏
     */
    private boolean collect;
    /**
     * 收藏时间
     */
    private long collectTime;

    @Generated(hash = 3342184)
    public Word() {
    }

    public Word(long id) {
        this.id = id;
    }

    @Generated(hash = 1583594846)
    public Word(long id, @NotNull String text, String accents, String content, int index, boolean collect, long collectTime) {
        this.id = id;
        this.text = text;
        this.accents = accents;
        this.content = content;
        this.index = index;
        this.collect = collect;
        this.collectTime = collectTime;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @NotNull
    public String getText() {
        return text;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setText(@NotNull String text) {
        this.text = text;
    }

    public String getAccents() {
        return accents;
    }

    public void setAccents(String accents) {
        this.accents = accents;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public int getIndex() {
        return index;
    }

    public void setIndex(int index) {
        this.index = index;
    }

    public boolean getCollect() {
        return collect;
    }

    public void setCollect(boolean collect) {
        this.collect = collect;
    }

    public long getCollectTime() {
        return collectTime;
    }

    public void setCollectTime(long collectTime) {
        this.collectTime = collectTime;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeLong(this.id);
        dest.writeString(this.text);
        dest.writeString(this.accents);
        dest.writeString(this.content);
        dest.writeInt(this.index);
        dest.writeByte(this.collect ? (byte) 1 : (byte) 0);
        dest.writeLong(this.collectTime);
    }

    protected Word(Parcel in) {
        this.id = in.readLong();
        this.text = in.readString();
        this.accents = in.readString();
        this.content = in.readString();
        this.index = in.readInt();
        this.collect = in.readByte() != 0;
        this.collectTime = in.readLong();
    }

    public static final Parcelable.Creator<Word> CREATOR = new Creator<Word>() {
        @Override
        public Word createFromParcel(Parcel source) {
            return new Word(source);
        }

        @Override
        public Word[] newArray(int size) {
            return new Word[size];
        }
    };
}
