package com.qwwuyu.recite.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * @Description单词Entity
 * @author qw
 * @date 2015-12-28
 */
public class Word implements Serializable{

    /**
     * id
     */
    private long id;
    /** Not-null value. */
    /**
     * 单词文本
     */
    private String text;
    /**
     * 音标
     */
    private String accents;
    /**
     * 单词介绍
     */
    private String content;
    /**
     * 乱序角标
     */
    private Integer index;

    public Word() {
    }

    public Word(long id) {
        this.id = id;
    }

    public Word(long id, String text, String accents, String content, Integer index) {
        this.id = id;
        this.text = text;
        this.accents = accents;
        this.content = content;
        this.index = index;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getText() {
        return text;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setText(String text) {
        this.text = text;
    }

    public String getAccents() {
        return accents;
    }

    public void setAccents(String accents) {
        this.accents = accents;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Integer getIndex() {
        return index;
    }

    public void setIndex(Integer index) {
        this.index = index;
    }

}
